# Generated by Django 4.1.7 on 2023-03-23 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date_posted', models.DateField()),
                ('content', models.TextField()),
                ('image', models.TextField()),
                ('thumbnail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('image', models.TextField()),
                ('location', models.TextField()),
                ('thumbnail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('location', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('travel_from', models.TextField()),
                ('travel_to', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('date_registered', models.DateField()),
                ('username', models.TextField()),
                ('bio', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TripLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacationistaapi.leg')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacationistaapi.trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacationistaapi.user'),
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_from', models.TextField()),
                ('travel_to', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comment', models.TextField()),
                ('round_trip', models.BooleanField()),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacationistaapi.leg')),
                ('transportation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacationistaapi.transportationtype')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacationistaapi.trip')),
            ],
        ),
        migrations.AddField(
            model_name='leg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacationistaapi.user'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comment', models.TextField()),
                ('title', models.TextField()),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacationistaapi.expensetype')),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacationistaapi.leg')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacationistaapi.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacationistaapi.eventtype')),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacationistaapi.leg')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacationistaapi.trip')),
            ],
        ),
    ]
